version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: taxi_web
    # '/start' is the shell script used to run the service
    command: /start
    # this volume is used to map the files and folders on the host to the container
    # so if we change code on the host, code in the docker container will also be changed
    volumes:
      - .:/app
    ports:
      - 8930:8930
    expose:
      - 8930
    # env_file is used to manage the env variables of our project
    env_file:
      - ./.env/.dev-sample
    depends_on:
      - redis
      - db
    container_name: taxi_web
    networks:
      - taxi-network    
    

  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=taxi
      - POSTGRES_USER=taxi
      - POSTGRES_PASSWORD=taxi
      - TZ=Asia/Seoul
    ports:
      - 54323:5432
    container_name: taxi_db
    networks:
      - taxi-network    
    

  redis:
    image: redis:5-alpine
    container_name: taxi_redis
    networks:
      - taxi-network
    

  celery_worker:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: django_celery_example_celery_worker
    command: /start-celeryworker
    volumes:
      - .:/app
    env_file:
      - ./.env/.dev-sample
    depends_on:
      - redis
      - db
    container_name: taxi_celery_worker
    networks:
      - taxi-network

  celery_beat:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: django_celery_example_celery_beat
    command: /start-celerybeat
    volumes:
      - .:/app
    env_file:
      - ./.env/.dev-sample
    depends_on:
      - redis
      - db
    container_name: taxi_celery_beat
    networks:
      - taxi-network

  flower:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: django_celery_example_celey_flower
    command: /start-flower
    volumes:
      - .:/app
    env_file:
      - ./.env/.dev-sample
    ports:
      - 5557:5555
    depends_on:
      - redis
      - db
    container_name: taxi_celery_flower
    networks:
      - taxi-network

volumes:
  postgres_data:

networks:
  taxi-network:
    driver: bridge
